export const enum CronExpressions {
  EveryMinute = '* * * * *',
  Every5Minutes = '*/5 * * * *',
  Every10Minutes = '*/10 * * * *',
  Every15Minutes = '*/15 * * * *',
  Every30Minutes = '*/30 * * * *',
  EveryHour = '0 * * * *',
  Every2Hours = '0 */2 * * *',
  Every6Hours = '0 */6 * * *',
  Every12Hours = '0 */12 * * *',
  EveryDayAtMidnight = '0 0 * * *',
  EveryDayAtNoon = '0 12 * * *',
  EveryMonday = '0 0 * * 1',
  EveryWeek = '0 0 * * 0',
  EveryMonth = '0 0 1 * *',
  EveryYear = '0 0 1 1 *',
}
